// ============================================================
// Style and format presets.
// STYLE preset = colors + fonts. Change via ACTIVE_PRESET in slides.ts.
// FORMAT preset = canvas dimensions per platform. Change via DEFAULT_FORMAT.
// ============================================================

import type { StylePreset, FormatPreset, FormatId } from "./types";

export const FORMAT_PRESETS: Record<FormatId, FormatPreset> = {
  "threads-4x5": {
    id: "threads-4x5",
    name: "Threads / Instagram 4:5",
    w: 1080,
    h: 1350,
    platform: "Threads, Instagram",
  },
  "instagram-square": {
    id: "instagram-square",
    name: "Square 1:1",
    w: 1080,
    h: 1080,
    platform: "Instagram, Facebook, LinkedIn",
  },
  "linkedin-square": {
    id: "linkedin-square",
    name: "LinkedIn PDF",
    w: 1080,
    h: 1080,
    platform: "LinkedIn (PDF document)",
  },
  "tiktok-9x16": {
    id: "tiktok-9x16",
    name: "TikTok 9:16",
    w: 1080,
    h: 1920,
    platform: "TikTok, Reels, Shorts",
  },
  "story-9x16": {
    id: "story-9x16",
    name: "Story 9:16",
    w: 1080,
    h: 1920,
    platform: "Instagram Stories, Threads",
  },
};

export const PRESETS: Record<string, StylePreset> = {
  "minimal-dark": {
    id: "minimal-dark",
    name: "Minimal Dark",
    bg: "#0A0A0A",
    textColor: "#FFFFFF",
    textSecondary: "rgba(255,255,255,0.5)",
    accentColor: "#FFFFFF",
    highlightColor: "#FACC15",
    fontFamily: "var(--font-space-grotesk), var(--font-inter)",
    hookFontFamily: "var(--font-unbounded)",
  },
  "minimal-light": {
    id: "minimal-light",
    name: "Minimal Light",
    bg: "#FAFAFA",
    textColor: "#1A1A1A",
    textSecondary: "rgba(0,0,0,0.4)",
    accentColor: "#1A1A1A",
    highlightColor: "#DC2626",
    fontFamily: "var(--font-inter)",
  },
  "gradient-bold": {
    id: "gradient-bold",
    name: "Gradient Bold",
    bg: "#1a1a2e",
    bgGradient: "linear-gradient(135deg, #6366F1 0%, #EC4899 50%, #F59E0B 100%)",
    textColor: "#FFFFFF",
    textSecondary: "rgba(255,255,255,0.7)",
    accentColor: "#FFFFFF",
    highlightColor: "#FDE047",
    fontFamily: "var(--font-inter)",
  },
  paper: {
    id: "paper",
    name: "Paper",
    bg: "#F5F0E8",
    textColor: "#2C2416",
    textSecondary: "rgba(44,36,22,0.5)",
    accentColor: "#8B7355",
    highlightColor: "#B91C1C",
    fontFamily: "var(--font-playfair)",
    hookFontFamily: "var(--font-playfair)",
  },
  editorial: {
    id: "editorial",
    name: "Editorial",
    bg: "#FFFFFF",
    textColor: "#111111",
    textSecondary: "rgba(0,0,0,0.35)",
    accentColor: "#111111",
    highlightColor: "#E11D48",
    fontFamily: "var(--font-playfair)",
    hookFontFamily: "var(--font-playfair)",
  },
  brutalist: {
    id: "brutalist",
    name: "Brutalist",
    bg: "#FFFFFF",
    textColor: "#000000",
    textSecondary: "rgba(0,0,0,0.5)",
    accentColor: "#000000",
    highlightColor: "#22C55E",
    fontFamily: "var(--font-space-grotesk)",
    hookFontFamily: "var(--font-unbounded)",
  },
  pastel: {
    id: "pastel",
    name: "Pastel",
    bg: "#EDE9FE",
    textColor: "#1E1B4B",
    textSecondary: "rgba(30,27,75,0.45)",
    accentColor: "#6D28D9",
    highlightColor: "#C026D3",
    fontFamily: "var(--font-inter)",
  },
  neon: {
    id: "neon",
    name: "Neon",
    bg: "#0F172A",
    bgGradient: "linear-gradient(160deg, #0F172A 0%, #1E1B4B 100%)",
    textColor: "#E0F2FE",
    textSecondary: "rgba(224,242,254,0.4)",
    accentColor: "#06B6D4",
    highlightColor: "#A855F7",
    fontFamily: "var(--font-space-grotesk)",
    hookFontFamily: "var(--font-unbounded)",
  },
  custom: {
    id: "custom",
    name: "Custom",
    bg: "#0A0A0A",
    textColor: "#FFFFFF",
    textSecondary: "rgba(255,255,255,0.5)",
    accentColor: "#6366F1",
    highlightColor: "#FACC15",
    fontFamily: "var(--font-inter)",
  },
};
